recipe: default.v1
assistant_id: 20250729-135718-wicker-pole
language: es

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 3
    epochs: 50
